esphome:
  name: touch-kitchen
  friendly_name: Touch Kitchen

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Touch Kitchen Fallback"

esp32_touch:
  setup_mode: false

binary_sensor:
  - platform: esp32_touch
    name: "Kitchen Touch"
    pin: GPIO13
    threshold: 1000
